---
requests:
  -
    condition: github_event == 'discussion' && payload.action == 'created'
    action: transform
    transform:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: '{{ payload.discussion.category.emoji }} Discussion created by <{{ payload.sender.html_url }}|{{ payload.sender.login }}>'
        - type: section
          text:
            type: mrkdwn
            text: "{{ quote(shorten_lines_md('*<' + payload.discussion.html_url + '|#' + string(payload.discussion.number) + ' ' + payload.discussion.title + '>*' + '\n' + payload.discussion.body, 10, '<' + payload.discussion.html_url + '|View more>')) }}"
        - type: context
          elements:
            -
              type: mrkdwn
              text: 'Created by <{{ payload.sender.html_url }}|{{ payload.sender.login }}> on <{{ payload.discussion.html_url }} | {{ payload.repository.full_name }}>'
  -
    condition: github_event == 'discussion_comment' && payload.action == 'created'
    action: transform
    transform:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: 'New comment by <{{ payload.sender.html_url }}|{{ payload.sender.login }}> on discussion <{{ payload.comment.html_url }}|#{{ string(payload.discussion.number) }} {{ payload.discussion.title }} >'
        - type: section
          text:
            type: mrkdwn
            text: "{{ quote(shorten_lines_md(payload.comment.body, 10, '<' + payload.comment.html_url + '|View more>')) }}"
        - type: context
          elements:
            -
              type: mrkdwn
              text: 'Commented by <{{ payload.sender.html_url }}|{{ payload.sender.login }}> on <{{ payload.comment.html_url }} | {{ payload.repository.full_name }}>'
  -
    condition: github_event == 'discussion' && payload.action == 'answered'
    action: transform
    transform:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: ':tada: Marked as answer by <{{ payload.sender.html_url }}|{{ payload.sender.login }}> on discussion <{{ payload.answer.html_url }}|#{{ string(payload.discussion.number) }} {{ payload.discussion.title }} >'
        - type: section
          text:
            type: mrkdwn
            text: '{{ payload.answer.html_url }} by <{{ payload.answer.user.html_url }}|{{ payload.answer.user.login }}>'
        - type: context
          elements:
            -
              type: mrkdwn
              text: 'Marked by <{{ payload.sender.html_url }}|{{ payload.sender.login }}> on <{{ payload.answer.html_url }} | {{ payload.repository.full_name }}>'
  -
    condition: github_event == 'ping'
    action: transform
    transform:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: 'Set octoslack to <{{ payload.repository.html_url }}|{{ payload.repository.full_name }} >'
