---
requests:
  -
    condition: github_event == 'discussion' && payload.action == 'created'
    transform:
      blocks:
        - type: section
          text:
            type: mrkdwn
            text: |-
              Discussion created by {{ payload.user.login }}
        - type: section
          text:
            type: mrkdwn
            text: |-
              {{ quote(payload.discussion.body) }}
